/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Account service. Represents a row in the &quot;AMF_Account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.model.impl.AccountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.model.impl.AccountImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Account
 * @generated
 */
@ProviderType
public interface AccountModel
	extends BaseModel<Account>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account model instance should use the {@link Account} interface instead.
	 */

	/**
	 * Returns the primary key of this account.
	 *
	 * @return the primary key of this account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account.
	 *
	 * @param primaryKey the primary key of this account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this account.
	 *
	 * @return the uuid of this account
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this account.
	 *
	 * @param uuid the uuid of this account
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the account ID of this account.
	 *
	 * @return the account ID of this account
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account.
	 *
	 * @param accountId the account ID of this account
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the group ID of this account.
	 *
	 * @return the group ID of this account
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this account.
	 *
	 * @param groupId the group ID of this account
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this account.
	 *
	 * @return the company ID of this account
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account.
	 *
	 * @param companyId the company ID of this account
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account.
	 *
	 * @return the user ID of this account
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this account.
	 *
	 * @param userId the user ID of this account
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account.
	 *
	 * @return the user uuid of this account
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this account.
	 *
	 * @param userUuid the user uuid of this account
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this account.
	 *
	 * @return the user name of this account
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this account.
	 *
	 * @param userName the user name of this account
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this account.
	 *
	 * @return the create date of this account
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account.
	 *
	 * @param createDate the create date of this account
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account.
	 *
	 * @return the modified date of this account
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account.
	 *
	 * @param modifiedDate the modified date of this account
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first_name of this account.
	 *
	 * @return the first_name of this account
	 */
	@AutoEscape
	public String getFirst_name();

	/**
	 * Sets the first_name of this account.
	 *
	 * @param first_name the first_name of this account
	 */
	public void setFirst_name(String first_name);

	/**
	 * Returns the last_name of this account.
	 *
	 * @return the last_name of this account
	 */
	@AutoEscape
	public String getLast_name();

	/**
	 * Sets the last_name of this account.
	 *
	 * @param last_name the last_name of this account
	 */
	public void setLast_name(String last_name);

	/**
	 * Returns the user_name of this account.
	 *
	 * @return the user_name of this account
	 */
	@AutoEscape
	public String getUser_name();

	/**
	 * Sets the user_name of this account.
	 *
	 * @param user_name the user_name of this account
	 */
	public void setUser_name(String user_name);

	/**
	 * Returns the email_address of this account.
	 *
	 * @return the email_address of this account
	 */
	@AutoEscape
	public String getEmail_address();

	/**
	 * Sets the email_address of this account.
	 *
	 * @param email_address the email_address of this account
	 */
	public void setEmail_address(String email_address);

	/**
	 * Returns the gender of this account.
	 *
	 * @return the gender of this account
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this account.
	 *
	 * @param gender the gender of this account
	 */
	public void setGender(String gender);

	/**
	 * Returns the birthday of this account.
	 *
	 * @return the birthday of this account
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this account.
	 *
	 * @param birthday the birthday of this account
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the password of this account.
	 *
	 * @return the password of this account
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this account.
	 *
	 * @param password the password of this account
	 */
	public void setPassword(String password);

	/**
	 * Returns the home_phone of this account.
	 *
	 * @return the home_phone of this account
	 */
	public int getHome_phone();

	/**
	 * Sets the home_phone of this account.
	 *
	 * @param home_phone the home_phone of this account
	 */
	public void setHome_phone(int home_phone);

	/**
	 * Returns the mobile_phone of this account.
	 *
	 * @return the mobile_phone of this account
	 */
	public int getMobile_phone();

	/**
	 * Sets the mobile_phone of this account.
	 *
	 * @param mobile_phone the mobile_phone of this account
	 */
	public void setMobile_phone(int mobile_phone);

	/**
	 * Returns the address of this account.
	 *
	 * @return the address of this account
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this account.
	 *
	 * @param address the address of this account
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this account.
	 *
	 * @return the address2 of this account
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this account.
	 *
	 * @param address2 the address2 of this account
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this account.
	 *
	 * @return the city of this account
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this account.
	 *
	 * @param city the city of this account
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this account.
	 *
	 * @return the state of this account
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this account.
	 *
	 * @param state the state of this account
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this account.
	 *
	 * @return the zip of this account
	 */
	public int getZip();

	/**
	 * Sets the zip of this account.
	 *
	 * @param zip the zip of this account
	 */
	public void setZip(int zip);

	/**
	 * Returns the security_question of this account.
	 *
	 * @return the security_question of this account
	 */
	@AutoEscape
	public String getSecurity_question();

	/**
	 * Sets the security_question of this account.
	 *
	 * @param security_question the security_question of this account
	 */
	public void setSecurity_question(String security_question);

	/**
	 * Returns the security_answer of this account.
	 *
	 * @return the security_answer of this account
	 */
	@AutoEscape
	public String getSecurity_answer();

	/**
	 * Sets the security_answer of this account.
	 *
	 * @param security_answer the security_answer of this account
	 */
	public void setSecurity_answer(String security_answer);

	/**
	 * Returns the accepted_tou of this account.
	 *
	 * @return the accepted_tou of this account
	 */
	@AutoEscape
	public String getAccepted_tou();

	/**
	 * Sets the accepted_tou of this account.
	 *
	 * @param accepted_tou the accepted_tou of this account
	 */
	public void setAccepted_tou(String accepted_tou);

	@Override
	public Account cloneWithOriginalValues();

}